version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: autocare-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: autocare-pro
    volumes:
      - mongodb_data:/data/db
    networks:
      - autocare-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: autocare-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/autocare-pro?authSource=admin
      JWT_SECRET: autocare-pro-production-secret-change-this
      ADMIN_PASSWORD: autocarpro12k@12k.wwc
      FRONTEND_URL: http://localhost:3000
      SOCKET_CORS_ORIGIN: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - autocare-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: autocare-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_BASE_URL: http://localhost:3001/api
      VITE_SOCKET_URL: http://localhost:3001
    depends_on:
      - backend
    networks:
      - autocare-network

volumes:
  mongodb_data:

networks:
  autocare-network:
    driver: bridge